In [2]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns
%matplotlib inline

In [3]:
from sklearn.datasets import make_classification

In [4]:
##create the dataset

X,Y=make_classification(n_samples=100,n_features=10,n_classes=2,random_state=42)

In [5]:
pd.DataFrame(X)

0         1         2         3         4         5         6  \
0  -1.140526  1.359706  0.861991  0.846092  0.606010 -1.556629  1.754794   
1  -0.078734 -1.329332  0.627375 -1.193006 -0.773010  0.097676  0.497998   
2   0.807427  0.730198 -1.285680  0.889484 -1.804882 -0.763259  0.048085   
3   0.588465 -0.375121 -0.575002 -0.149518 -0.563725  0.412931  0.243687   
4   1.636312 -1.640607 -1.360456 -0.941163 -1.430141  1.632411  0.130741   
..       ...       ...       ...       ...       ...       ...       ...   
95  0.531047  0.948005 -1.032233  0.996309 -1.008086 -2.038125 -0.351513   
96 -0.963142  0.556003  0.964233  0.193754 -0.703176  1.149273  1.770801   
97  0.950573 -2.255540 -0.270624 -1.692005  0.504047 -0.985726 -0.792873   
98 -1.016951  0.554484  1.031102  0.175930  0.615936 -1.081063 -0.309546   
99  1.897924 -1.614533 -1.693028 -0.838070  0.791663  1.158111  0.628346   

           7         8         9  
0   1.696456 -1.280429 -2.081929  
1   0.959271  0.024510  1.451144  
2  -0.904317 -1.627542  0.259723  
3  -0.506943 -0.822220  0.244967  
4  -1.435862 -0.440044  1.441273  
..       ...       ...       ...  
95  1.676437 -1.870792  0.018418  
96  1.812449 -0.034988 -0.626967  
97 -1.035242 -0.530258 -0.107030  
98 -1.251114  0.593101  0.326133  
99 -0.897254  0.624120 -0.012247  

[100 rows x 10 columns]

In [6]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.30,random_state=42)

In [7]:
#model training
from sklearn.linear_model import LogisticRegression
logistic=LogisticRegression()

In [8]:
logistic.fit(X_train,Y_train)

LogisticRegression()

In [9]:
Y_pred=logistic.predict(X_test)
Y_pred

array([0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 1, 1, 1, 1, 1, 1])

In [10]:
logistic.predict_proba(X_test)

array([[7.49632742e-01, 2.50367258e-01],
       [5.71492961e-02, 9.42850704e-01],
       [8.47383467e-03, 9.91526165e-01],
       [3.84386602e-02, 9.61561340e-01],
       [2.79853023e-02, 9.72014698e-01],
       [9.64640318e-01, 3.53596817e-02],
       [9.65369374e-01, 3.46306260e-02],
       [2.13024820e-01, 7.86975180e-01],
       [2.27546362e-01, 7.72453638e-01],
       [1.81401566e-01, 8.18598434e-01],
       [9.87298049e-01, 1.27019510e-02],
       [1.84390109e-03, 9.98156099e-01],
       [1.11638160e-03, 9.98883618e-01],
       [9.98846835e-01, 1.15316489e-03],
       [3.19528899e-03, 9.96804711e-01],
       [9.75335190e-01, 2.46648100e-02],
       [2.79003416e-02, 9.72099658e-01],
       [9.72840626e-01, 2.71593739e-02],
       [9.57717728e-01, 4.22822718e-02],
       [9.96764165e-01, 3.23583540e-03],
       [3.26255970e-02, 9.67374403e-01],
       [9.91543744e-01, 8.45625612e-03],
       [6.48321099e-01, 3.51678901e-01],
       [9.99581102e-01, 4.18898067e-04],
       [4.128605

In [11]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [12]:
score=accuracy_score(Y_test,Y_pred)
print("accuracy score:",score)
cm=confusion_matrix(Y_test,Y_pred)
print("confusion_matrix:",cm)
print(classification_report(Y_test,Y_pred))

accuracy score: 0.9333333333333333
confusion_matrix: [[12  2]
 [ 0 16]]
              precision    recall  f1-score   support

           0       1.00      0.86      0.92        14
           1       0.89      1.00      0.94        16

    accuracy                           0.93        30
   macro avg       0.94      0.93      0.93        30
weighted avg       0.94      0.93      0.93        30



In [31]:
#Hyperparameter tuning and cross validation
param_grid = {
    'solver': ['liblinear', 'saga'],
    'penalty': ['l1', 'l2'],
    'C': [0.01, 0.1, 1, 10]
}
model=LogisticRegression()
param_grid


{'solver': ['liblinear', 'saga'],
 'penalty': ['l1', 'l2'],
 'C': [0.01, 0.1, 1, 10]}

In [32]:
from sklearn.model_selection import StratifiedKFold
cv=StratifiedKFold()

In [33]:
##Grid Search CV
# try to find best parameters
from sklearn.model_selection import GridSearchCV
grid=GridSearchCV(estimator=model,param_grid=param_grid,scoring='accuracy',cv=cv,n_jobs=-1)

In [25]:
grid

GridSearchCV(cv=5, error_score='raise', estimator=LogisticRegression(),
             param_grid={'C': [100, 10, 1.0, 0.1, 0.01],
                         'penalty': ['l1', 'l2', 'elasticnet'],
                         'solver': ['lbfgs', 'liblinear', 'newton-cg',
                                    'newton-cholesky', 'sag', 'saga']})

In [34]:

grid.fit(X_train, Y_train)


GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': [0.01, 0.1, 1, 10], 'penalty': ['l1', 'l2'],
                         'solver': ['liblinear', 'saga']},
             scoring='accuracy')

In [35]:
grid.best_estimator_

LogisticRegression(C=1, penalty='l1', solver='liblinear')

In [36]:
grid.best_score_

0.9857142857142858

In [38]:
Y_pred=grid.predict(X_test)
Y_pred

array([0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 1, 1, 1, 1])

In [ ]:
#after appying best parameters
score=accuracy_score(Y_test,Y_pred)
print("accuracy score:",score)
cm=confusion_matrix(Y_test,Y_pred)
print("confusion_matrix:",cm)
print(classification_report(Y_test,Y_pred))

accuracy score: 0.9666666666666667
confusion_matrix: [[13  1]
 [ 0 16]]
              precision    recall  f1-score   support

           0       1.00      0.93      0.96        14
           1       0.94      1.00      0.97        16

    accuracy                           0.97        30
   macro avg       0.97      0.96      0.97        30
weighted avg       0.97      0.97      0.97        30



Randomized Search  CV


In [42]:
from sklearn.model_selection import RandomizedSearchCV
randomcv=RandomizedSearchCV(estimator=model,param_distributions=param_grid,cv=5,scoring='accuracy')

In [43]:
randomcv.fit(X_train,Y_train)

c:\Users\LENOVO\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\Users\LENOVO\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\Users\LENOVO\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\Users\LENOVO\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\Users\LENOVO\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\Users\LENOVO\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:349: ConvergenceWarning: The max

RandomizedSearchCV(cv=5, estimator=LogisticRegression(),
                   param_distributions={'C': [0.01, 0.1, 1, 10],
                                        'penalty': ['l1', 'l2'],
                                        'solver': ['liblinear', 'saga']},
                   scoring='accuracy')

In [44]:
randomcv.best_params_

{'solver': 'saga', 'penalty': 'l1', 'C': 10}

In [45]:
randomcv.best_score_

0.9857142857142858

In [46]:
Y_pred=randomcv.predict(X_test)

In [47]:
#after appying best parameters
score=accuracy_score(Y_test,Y_pred)
print("accuracy score:",score)
cm=confusion_matrix(Y_test,Y_pred)
print("confusion_matrix:",cm)
print(classification_report(Y_test,Y_pred))

accuracy score: 0.9
confusion_matrix: [[11  3]
 [ 0 16]]
              precision    recall  f1-score   support

           0       1.00      0.79      0.88        14
           1       0.84      1.00      0.91        16

    accuracy                           0.90        30
   macro avg       0.92      0.89      0.90        30
weighted avg       0.92      0.90      0.90        30

